permissions:
  contents: read

name: Code Quality
on:
  push:
    branches:
      - 35-task-setup-github-actions
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    name: "Lint code"
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Install language and dependencies 
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
        run: pip install -r requirements.txt
      - name: "Lint code"
        run: pylint --fail-under=8 **.py
  test:
    name: "Test code"
    runs-on: ubuntu-latest
    steps:
      - name: Install language and dependencies 
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
        run: pip install -r requirements.txt
      - name: "Run tests"
        run: pytest